---
# Ansible Tasks for Cowrie SSH/Telnet Honeypot
##############################################

# Available tags:
# - debug
# - never
# - always
# - update
# - root      -- this tags require sudo access
# - docker    -- for use with docker

# These tasks need to be executed as root
##############################################

- name: Cowrie | ensure no conflict with default ssh server
  tag: [root]
  become: true
  lineinfile:
    - dest: '/etc/ssh/sshd_config'
      regexp: '^Port 22$'
      line: 'Port {{ real_ssh_port }}'
  notify:
    - restart ssh
  when: real_ssh_port is defined and real_ssh_port != '' and real_ssh_port != 22

- name: Redirect port 22 to 2222
  become: true
  tag: [root]
  iptables:
    table: nat
    chain: PREROUTING
    protocol: tcp
    match: tcp
    destination_port: 22
    jump: REDIRECT
    to_ports: 2222
    comment: Redirect ssh traffic to port 2222

- name: Redirect port 23 to 2223
  become: true
  tag: [root]
  iptables:
    table: nat
    chain: PREROUTING
    protocol: tcp
    match: tcp
    destination_port: 23
    jump: REDIRECT
    to_ports: 2223
    comment: Redirect telnet traffic to port 2223
