---
# Ansible Tasks for Cowrie SSH/Telnet Honeypot
##############################################

# Available tags:
# - debug
# - never
# - always
# - update
# - root      -- this tags require sudo access
# - docker    -- for use with docker
##############################################

- import_tasks: cowrie-os.yaml
  tags:
    - cowrie
    - root

- import_tasks: cowrie-venv.yaml
  become: true
  become_user: "{{ cowrie_user }}"
  tags:
    - cowrie
    - python
    - virtualenv

# Install Cowrie
################

- name: Git clone Cowrie repository
  tags: [git]
  become: true
  become_user: "{{ cowrie_user }}"
  git:
    repo: "{{ cowrie_repo }}"
    dest: "{{ cowrie_dir }}"
    force: true

# TODO: needs to pull
- name: Git pull Cowrie repository
  tags: [git, never]
  become: true
  become_user: "{{ cowrie_user }}"
  git:
    repo: "{{ cowrie_repo }}"
    dest: "{{ cowrie_dir }}"
    force: true

- name: Install Cowrie config file
  tags: [cfg]
  become: true
  become_user: "{{ cowrie_user }}"
  template:
    src: ../templates/cowrie.cfg.j2
    dest: "{{ cowrie_dir }}/etc/cowrie.cfg"

- import_tasks: cowrie-startup.yaml
  become: true
  tags:
    - cowrie
    - root
