---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: instance-centos7
    image: centos:7
  - name: instance-debian-jessie
    image: debian:jessie
  - name: instance-debian-stretch
    image: debian:stretch
  - name: instance-ubuntu-trusty
    image: ubuntu:trusty
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
