---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: instance-centos7
    image: centos:7
  - name: instance-redhat6
    image: redhat:6
  - name: instance-redhat7
    image: redhat:7
  - name: instance-debian-wheezy
    image: debian:wheezy
  - name: instance-debian-stretch
    image: debian:stretch
  - name: instance-debian-sid
    image: debian:sid
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
